[project]
name = "stlclash"
version = "0.1.0"
description = "A benchmark and suite of control environments for multi-objective control with STL specifications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "morl-baselines",
    "rlrom",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]

[tool.mypy]
disable_error_code = ["import-untyped"]

[tool.uv.sources]
morl-baselines = { git = "https://github.com/LucasAlegre/morl-baselines.git" }
rlrom = { git = "https://github.com/decyphir/rlrom.git", branch = "multi-objective" }
